# Generated by Django 5.2 on 2025-07-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='episode_selector_opened',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='season_reached',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='view_artists',
        ),
    ]
