# Generated by Django 5.2 on 2026-01-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_home_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shows_per_page',
            field=models.IntegerField(default='5'),
        ),
    ]
