# Generated by Django 5.2 on 2025-06-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_alter_show_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='users',
        ),
    ]
