# Generated by Django 5.2 on 2026-01-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_remove_show_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.CharField(default='2026', max_length=25),
        ),
    ]
