# Generated by Django 6.0.1 on 2026-01-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0006_alter_show_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="popup",
            field=models.TextField(
                blank=True,
                default="\n    <div class='alert alert-dismissible fade show alert-info' role='alert'>\n    <h4 class='alert-heading'>Well done!</h4>\n    <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>\n    <hr>\n    <p class='mb-0'>Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>\n    <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close' onclick='popupClosed();'></button>\n    </div>",
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="rating",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="shows.rating",
            ),
        ),
    ]
