# Generated by Django 5.2 on 2025-06-24 14:52

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='shows', to='shows.genre'),
        ),
        migrations.AddField(
            model_name='show',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='shows', to='shows.label'),
        ),
        migrations.AddField(
            model_name='show',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='shows', to='shows.language'),
        ),
        migrations.AddField(
            model_name='show',
            name='rating',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shows.rating'),
        ),
        migrations.AddField(
            model_name='show',
            name='users',
            field=models.ManyToManyField(blank=True, default=django.db.models.manager.BaseManager.all, related_name='shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_shows', to=settings.AUTH_USER_MODEL),
        ),
    ]
