# Generated by Django 5.2 on 2025-06-23 13:24

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='users',
            field=models.ManyToManyField(blank=True, default=django.db.models.manager.BaseManager.all, related_name='shows', to=settings.AUTH_USER_MODEL),
        ),
    ]
