# Generated by Django 5.2 on 2025-06-25 11:53

import users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_autoplay_customuser_episode_reached_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=users.storage.OverwriteStorage(), upload_to=users.storage.File_Rename('users/profile_pic/')),
        ),
    ]
