# Generated by Django 5.2 on 2025-07-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_episode_selector_opened_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='episode_reached',
            new_name='reached',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='time_reached',
        ),
    ]
