# Generated by Django 5.2 on 2026-01-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_episode_reached_customuser_reached_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='home_tab',
            field=models.CharField(default='new', max_length=10),
        ),
    ]
